---
- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present

- name: Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started
    enabled: yes

# TODO: créer base et users via postgresql_db/postgresql_user modules
