- hosts: managed_containers
  become: yes
  roles:
    - users

- hosts: webservers
  become: yes
  roles:
    - web

- hosts: databases
  become: yes
  roles:
    - db

- hosts: monitoring
  become: yes
  roles:
    - grafana

- hosts: mail_relays
  become: yes
  roles:
    - mail_relay

- hosts: mailservers
  become: yes
  roles:
    - postfix
    - dovecot

- hosts: ai
  become: yes
  roles:
    - ollama

- hosts: backups
  become: yes
  roles:
    - backup
