- hosts: managed_containers
  become: yes
  serial: 1
  roles:
    - users

- hosts: databases
  become: yes
  roles:
    - db
    - db_logistia

- hosts: webservers
  become: yes
  roles:
    - web

- hosts: mail_relays
  become: yes
  roles:
    - mail_relay

- hosts: mailservers
  become: yes
  roles:
    - postfix
    - dovecot

- hosts: ai
  become: yes
  roles:
    - ollama

- hosts: mail_relays:mailservers
  become: yes
  roles:
    - mail_log_forwarder

- hosts: backups
  become: yes
  roles:
    - backup

- hosts: databases:mailservers
  become: yes
  roles:
    - backup_client

- hosts: managed_containers
  become: yes
  serial: 1
  roles:
    - hardening

- hosts: managed_containers
  become: yes
  serial: 1
  roles:
    - monitoring_exporter

- hosts: monitoring
  become: yes
  roles:
    - grafana
